from pydantic import BaseModel, Field

from models.finding import Severity


class PlanDecision(BaseModel):
    """
    Structured outcome schema for planner decisions generated by the AI provider.
    """
    selected_workflow: str = Field(..., description="Name of the selected workflow to execute")
    execution_strategy: str = Field(..., description="Execution strategy: sequential or parallel")
    reasoning: str = Field(..., description="Explain why this workflow choice was made")
    expected_outputs: list[str] = Field(default_factory=list, description="List of expected files/artifacts")
    confidence: float = Field(default=1.0, description="Confidence score from 0.0 to 1.0")
    estimated_duration: float = Field(default=0.0, description="Estimated duration in seconds")


class ValidatedFinding(BaseModel):
    """
    Model representing a validated security finding inside AI structured decisions.
    """
    tool: str = Field(..., description="Name of the tool that generated this finding")
    target: str = Field(..., description="Target host, IP, or subdomain identifier")
    data: dict = Field(default_factory=dict, description="Metadata key-values associated with the vulnerability")
    severity: Severity = Field(..., description="Severity level profile")
    description: str = Field(..., description="Text description detailing the finding")


class AnalysisDecision(BaseModel):
    """
    Structured validation outcome of triage and risk classification.
    """
    validated_findings: list[ValidatedFinding] = Field(default_factory=list, description="List of verified findings")
    reasoning: str = Field(..., description="Triage analyst validation reasoning details")
